[versions]
ktlint = "0.48.2"
ktor = "3.4.0"
log4j = "2.25.3"
kotlin = "2.3.0"
coroutines = "1.10.2"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }

[libraries]
junit = "org.junit.jupiter:junit-jupiter:6.0.2"
kotlin-cli = "org.jetbrains.kotlinx:kotlinx-cli-jvm:0.3.6"
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlin-logging = "io.github.microutils:kotlin-logging-jvm:3.0.5"
kotlin-serialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.10.0"
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
log4j-api-kotlin = "org.apache.logging.log4j:log4j-api-kotlin:1.5.0"
log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "log4j" }
log4j-slf4j2-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl", version.ref = "log4j" }
mockk = "io.mockk:mockk:1.14.7"
zip4j = "net.lingala.zip4j:zip4j:2.11.5"
